/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodproject;

/**
 *
 * @author Dell_5G
 */
public class AddUser extends javax.swing.JFrame {

    private UserDB userdb;
    private home myhome;
    private Add_User_Controller addC1;
    private String name;
    private String ID;
    private String address;
    private String phone;
    
    public AddUser(UserDB userdb,home myhome,Add_User_Controller addC1) {
        initComponents();
        this.userdb = userdb;
        this.myhome = myhome;
        this.addC1=addC1;
        this.setBounds( 350, 100,641, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Namelabel = new javax.swing.JLabel();
        Addbutton = new javax.swing.JButton();
        IDtextfield = new javax.swing.JTextField();
        AddUserlabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        Idlabel = new javax.swing.JLabel();
        Addresslabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Adresstextfield = new javax.swing.JTextField();
        Phonetextfield = new javax.swing.JTextField();
        Nametextfield = new javax.swing.JTextField();
        exitbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bro's Library");
        setMaximumSize(new java.awt.Dimension(547, 400));

        Namelabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Namelabel.setText("Name:");

        Addbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Addbutton.setText("Add");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        IDtextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        AddUserlabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        AddUserlabel.setText("Add User");

        PhoneLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone:");

        Idlabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Idlabel.setText("ID:");

        Addresslabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Addresslabel.setText("Address:");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        Adresstextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Phonetextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Nametextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        exitbutton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitbutton1.setText("Exit");
        exitbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddUserlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Namelabel)
                            .addComponent(Addresslabel)
                            .addComponent(PhoneLabel)
                            .addComponent(Idlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Adresstextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Phonetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(235, 235, 235)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddUserlabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namelabel)
                    .addComponent(Nametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idlabel)
                    .addComponent(IDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(Phonetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addresslabel)
                    .addComponent(Adresstextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbutton)
                    .addComponent(exitbutton1))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
        name = Nametextfield.getText();
        ID = IDtextfield.getText();
        address =  Adresstextfield.getText();
        phone = Phonetextfield.getText();
        
        addC1.getData(name, ID, address, phone);
        addC1.createUser();
        addC1.save(userdb);
        myhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void exitbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutton1ActionPerformed
        myhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitbutton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddUserlabel;
    private javax.swing.JButton Addbutton;
    private javax.swing.JLabel Addresslabel;
    private javax.swing.JTextField Adresstextfield;
    private javax.swing.JTextField IDtextfield;
    private javax.swing.JLabel Idlabel;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JTextField Nametextfield;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField Phonetextfield;
    private javax.swing.JButton exitbutton1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
