/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodproject;

/**
 *
 * @author Dell_5G
 */
public class BorrowBook extends javax.swing.JFrame {

    /**
     * Creates new form BorrowBook
     */
    protected home myHome;
    protected Borrow_book_controller borrowc1;
    protected UserDB udb;
    protected BooksInventory bdb;

    public BorrowBook(home myHome, Borrow_book_controller borrowc1,UserDB udb,BooksInventory bdb) {
        this.myHome = myHome;
        this.borrowc1 = borrowc1;
        this.udb=udb;
        this.bdb=bdb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        BorrowLabel = new javax.swing.JLabel();
        BookNamelabel = new javax.swing.JLabel();
        bookIdText = new javax.swing.JTextField();
        UserNamelabel = new javax.swing.JLabel();
        UserIDtextfield = new javax.swing.JTextField();
        Verifybutton = new javax.swing.JButton();
        Exitbutton1 = new javax.swing.JButton();

        jTextField6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bro's Library");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(600, 400));

        BorrowLabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        BorrowLabel.setText("Borrow Book");

        BookNamelabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BookNamelabel.setText("Book ID:");

        bookIdText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        UserNamelabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UserNamelabel.setText("User ID:");

        UserIDtextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UserIDtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDtextfieldActionPerformed(evt);
            }
        });

        Verifybutton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        Verifybutton.setText("Lend");
        Verifybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifybuttonActionPerformed(evt);
            }
        });

        Exitbutton1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        Exitbutton1.setText("Exit");
        Exitbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exitbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BorrowLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookNamelabel)
                            .addComponent(UserNamelabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserIDtextfield)
                            .addComponent(bookIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 209, Short.MAX_VALUE)
                .addComponent(Verifybutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exitbutton1)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BorrowLabel)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookNamelabel)
                    .addComponent(bookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNamelabel)
                    .addComponent(UserIDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Verifybutton)
                    .addComponent(Exitbutton1))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void UserIDtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDtextfieldActionPerformed

    private void Exitbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exitbutton1ActionPerformed
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Exitbutton1ActionPerformed

    private void VerifybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifybuttonActionPerformed
        borrowc1.getdata( UserIDtextfield.getText(),bookIdText.getText());
        borrowc1.update(bdb, udb);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VerifybuttonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookNamelabel;
    private javax.swing.JLabel BorrowLabel;
    private javax.swing.JButton Exitbutton1;
    private javax.swing.JTextField UserIDtextfield;
    private javax.swing.JLabel UserNamelabel;
    private javax.swing.JButton Verifybutton;
    private javax.swing.JTextField bookIdText;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
