/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodproject;

/**
 *
 * @author Dell_5G
 */
public class RemoveUser extends javax.swing.JFrame {

   private UserDB userdb;
    private home myHome;
    private remove_user_Controller remC2;
    private String ID;
    
    public RemoveUser(UserDB userdb,home myhome,remove_user_Controller remC2) {
        initComponents();
        this.userdb=userdb;
        this.myHome=myhome;
        this.remC2=remC2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Removeuserlabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        IDtextfield = new javax.swing.JTextField();
        Removebutton = new javax.swing.JButton();
        exitbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bro's Library");
        setMaximumSize(new java.awt.Dimension(600, 330));

        Removeuserlabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        Removeuserlabel.setText("Remove User");

        UserIDLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UserIDLabel.setText("User ID:");
        UserIDLabel.setToolTipText("");

        IDtextfield.setToolTipText("Enter ID of User you want to remove");
        IDtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtextfieldActionPerformed(evt);
            }
        });

        Removebutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Removebutton.setText("Remove");
        Removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovebuttonActionPerformed(evt);
            }
        });

        exitbutton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitbutton1.setText("Exit");
        exitbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Removeuserlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(UserIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Removebutton)
                .addGap(52, 52, 52)
                .addComponent(exitbutton1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Removeuserlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIDLabel))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Removebutton)
                    .addComponent(exitbutton1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtextfieldActionPerformed

    private void RemovebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovebuttonActionPerformed
        ID = IDtextfield.getText();
        remC2.getdata(ID);
        remC2.search(userdb);
        remC2.delete(userdb);
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RemovebuttonActionPerformed

    private void exitbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutton1ActionPerformed
        myHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitbutton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDtextfield;
    private javax.swing.JButton Removebutton;
    private javax.swing.JLabel Removeuserlabel;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JButton exitbutton1;
    // End of variables declaration//GEN-END:variables
}
