package oodproject;

public class ReturnBook extends javax.swing.JFrame {

    private home myhome;
    private return_book_controller returnc1;
    private UserDB userdb;
    private BooksInventory bookdb;
    
    public ReturnBook(home myhome,return_book_controller returnc1,UserDB userdb,BooksInventory bookdb) {
        initComponents();
        this.myhome=myhome;
        this.returnc1=returnc1;
        this.userdb=userdb;
        this.bookdb=bookdb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookNametextfield1 = new javax.swing.JTextField();
        Verifybutton = new javax.swing.JButton();
        Returnlabel = new javax.swing.JLabel();
        BookNamelabel = new javax.swing.JLabel();
        BookIDtextfield = new javax.swing.JTextField();
        Useridlabel = new javax.swing.JLabel();
        useridtextfield = new javax.swing.JTextField();
        Returnbutton = new javax.swing.JButton();
        Exitbutton1 = new javax.swing.JButton();

        BookNametextfield1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BookNametextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNametextfield1ActionPerformed(evt);
            }
        });

        Verifybutton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        Verifybutton.setText("Verify");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bro's Library");

        Returnlabel.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        Returnlabel.setText("Return Book");

        BookNamelabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BookNamelabel.setText("Book ID:");

        BookIDtextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BookIDtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDtextfieldActionPerformed(evt);
            }
        });

        Useridlabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Useridlabel.setText("User ID:");

        useridtextfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Returnbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Returnbutton.setText("Retrun");
        Returnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnbuttonActionPerformed(evt);
            }
        });

        Exitbutton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Exitbutton1.setText("Exit");
        Exitbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exitbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Returnlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Useridlabel)
                            .addComponent(BookNamelabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookIDtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(useridtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Returnbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Exitbutton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Returnlabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookNamelabel)
                    .addComponent(BookIDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Useridlabel)
                    .addComponent(useridtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Returnbutton)
                    .addComponent(Exitbutton1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookNametextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNametextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNametextfield1ActionPerformed

    private void BookIDtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDtextfieldActionPerformed

    private void Exitbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exitbutton1ActionPerformed
        myhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Exitbutton1ActionPerformed

    private void ReturnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnbuttonActionPerformed
        returnc1.getdata(useridtextfield.getText(),BookIDtextfield.getText());
        returnc1.update(bookdb, userdb);
        myhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnbuttonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BookIDtextfield;
    private javax.swing.JLabel BookNamelabel;
    private javax.swing.JTextField BookNametextfield1;
    private javax.swing.JButton Exitbutton1;
    private javax.swing.JButton Returnbutton;
    private javax.swing.JLabel Returnlabel;
    private javax.swing.JLabel Useridlabel;
    private javax.swing.JButton Verifybutton;
    private javax.swing.JTextField useridtextfield;
    // End of variables declaration//GEN-END:variables
}
